### ISSUE TITLE
bug alert

### ISSUE THREAD

**Issue by RIPISDRAD** [Seggan/EMC2#2]
hey there again
still 1.16.5 still java16 still latest version
i put 2 stack in the machne and i take 4 stack lol(netherwart)
i think u made a mistake not sure but with reason this is bad its gonna make people so reach witch u  wouldnt even dare to look at baltop
btw it works without the power or electricite still dont know a bug? have fun

**Comment by Seggan** [comment]
you mentioned on discord that you had put books in earlier. that gives extra qgp. also yes theyre supposed to run without energy
