### ISSUE TITLE
Confusing value changes

### ISSUE THREAD

**Issue by GingernutsMate** [Seggan/EMC2#20]
The cost/value of items changes seemingly at random. Can you please upload or explain the system behind why. It's very frustrating having something suddenly cost 5x as much as it did a second ago. Thanks.

**Comment by Sefiraat** [comment]
EMC2's EMC values are hard coded and no changes have been made to this repo in a while. There is no detail in this issue regarding the actual problem you are having. Please re-open describing the error/issue you are having both in more detail and with the required evidence to triage.

Thanks,
Sefi
